version: 2.0

jobs:
  build:
    machine:
      image: circleci/classic:latest
    working_directory: ~/
    steps:
      - run:
          name: Initialization environment
          command: |
            git clone https://github.com/betagouv/pass-culture-main.git
            cd pass-culture-main
            git clone https://github.com/betagouv/pass-culture-api.git api
            git clone https://github.com/betagouv/pass-culture-browser.git webapp
            git clone https://github.com/betagouv/pass-culture-pro.git pro
            ./install_lib_ci.sh
      - checkout:
          path: ~/pass-culture-main/shared
      - run:
          name: Running Unit Tests Pro
          command: |
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm use "$NODE_VERSION"
            cd ~/pass-culture-main/pro
            yarn install
            yarn test:unit
      - run:
          name: Running Unit Tests Webapp
          command: |
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm use "$NODE_VERSION"
            cd ~/pass-culture-main/webapp
            yarn install
            yarn test:unit
      - run:
          name: Install dockerize
          command: |
            wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
            sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
            rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.6.1
      - run:
          name: Run API server
          command: |
            cd ~/pass-culture-main
            docker-compose up
          background: true
      - run:
          name: Run Frontend Webapp (Prod version)
          command: |
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm use "$NODE_VERSION"
            cd ~/pass-culture-main/webapp
            yarn install
            yarn start
          background: true
      - run:
          name: Run Frontend Pro (Prod version)
          command: |
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm use "$NODE_VERSION"
            cd ~/pass-culture-main/pro
            dockerize -wait http://localhost:3000 -timeout 3m -wait-retry-interval 5s
            yarn install
            yarn start
          background: true
      - run:
          name: Running Sandbox
          command: |
            cd pass-culture-main
            dockerize -wait http://localhost/health -timeout 5m -wait-retry-interval 5s
            ./pc sandbox --name=industrial
      - run:
          name: Running tests Pro
          command: |
           export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm use "$NODE_VERSION"
            cd ~/pass-culture-main/pro
            yarn test:cafe
      - run:
          name: Reset all data
          command: |
            cd ~/pass-culture-main
            ./pc reset-all-db
            ./pc sandbox --name=industrial
      - run:
          name: Running tests Webapp
          command: |
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm use "$NODE_VERSION"
            cd ~/pass-culture-main/webapp
            yarn test:cafe

workflows:
  version: 2
  commit:
    jobs:
      - build
